version: 1.0.{build}
skip_tags: true
image: Visual Studio 2015
environment:
  nodejs_version: 5.11.0
install:
- ps: Install-Product node $env:nodejs_version x64
- cmd: npm install -g less
- cmd: npm install -g less-plugin-clean-css
build_script:
- cmd: lessc --no-color jenkins-dark.less ./dist/jenkins-dark.css
- ps: Compress-Archive -Path $(APPVEYOR_BUILD_FOLDER)/dist/*.css -DestinationPath ./dist/$(APPVEYOR_PROJECT_NAME)-$(APPVEYOR_BUILD_VERSION).zip
artifacts:
- path: dist/jenkins-dark.css
  name: css
- path: dist/*.zip
  name: zip
