version: 1.0.{build}
skip_tags: true
image: WMF 5
environment:
  nodejs_version: 5.11.0
install:
- ps: Install-Product node $env:nodejs_version x64
- cmd: npm install -g grunt-cli
- cmd: npm install -g grunt
- cmd: npm install -g less
- cmd: npm install -g less-plugin-clean-css
- cmd: npm update -g npm
- cmd: npm install
- ps: |
    $mvnVersion = '3.2.5'
    Add-Type -AssemblyName System.IO.Compression.FileSystem
    if (!(Test-Path -Path "C:\maven\")) {
      (new-object System.Net.WebClient).DownloadFile(
        "http://www.us.apache.org/dist/maven/maven-3/${mvnVersion}/binaries/apache-maven-${mvnVersion}-bin.zip",
        'c:\maven-bin.zip'
      )
      [System.IO.Compression.ZipFile]::ExtractToDirectory("C:\maven-bin.zip", "C:\maven")
    }
- cmd: SET PATH=C:\maven\apache-maven-3.2.5\bin;%JAVA_HOME%\bin;%PATH%
- cmd: SET MAVEN_OPTS=-XX:MaxPermSize=2g -Xmx4g
- cmd: SET JAVA_OPTS=-XX:MaxPermSize=2g -Xmx4g
build_script:
- cmd: grunt
- cmd: mkdir -p .\plugin\src\main\webapp
- cmd: xcopy .\dist\*.min.css .\plugin\src\main\webapp\ /h /i /c /k /y
- ps: Compress-Archive -Path "${env:APPVEYOR_BUILD_FOLDER}/dist/*.css" -DestinationPath "./dist/${env:APPVEYOR_PROJECT_NAME}-${env:APPVEYOR_BUILD_VERSION}.zip"
- ps: |
    if ( (Test-Path -Path ".\plugin\target") ) {
      Remove-Item -Path '.\plugin\target' | Out-Null;
    }
- cmd: |
    cd plugin
    mvn package
- cmd: xcopy plugin\target\*.hpi .\dist\${env:APPVEYOR_PROJECT_NAME}-${env:APPVEYOR_BUILD_VERSION}.hpi /h /c /k /y
artifacts:
- path: dist/jenkins-dark.css
  name: css
- path: dist/*.zip
  name: zip
- path: dist/*.hpi
  name: hpi
cache:
  - c:\maven\
  - c:\Users\appveyor\.m2\
deploy:
- provider: GitHub
  tag: $(APPVEYOR_PROJECT_NAME)-$(APPVEYOR_BUILD_VERSION)
  release: $(APPVEYOR_PROJECT_NAME)-$(APPVEYOR_BUILD_VERSION)
  auth_token:
    secure: Es5XTlIJiCiCFJHGDOA09AGFVZQL0jIWtUuPp4+m7MBcfeoVGbWQP2jYU3oSL5bw
  artifact: zip, hpi
  draft: false
  force_update: true
  on:
    branch: master
